import { Inter } from "next/font/google";
import DesktopNav from "./components/Navbar/DesktopNav/DesktopNav";
import "../styles/globals.css";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DesktopNav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
